import { useEffect, useState } from 'react';
import { Platform } from 'react-native';

/**
 * The browser's actually-visible viewport height in web px, tracking the
 * on-screen keyboard — or `null` on native, where this isn't needed.
 *
 * Why this exists: react-native-web's `Modal` renders `position: fixed; top:
 * 0; bottom: 0`, which mobile browsers pin to the *layout* viewport, not the
 * *visual* one. When the keyboard opens, the layout viewport does not shrink
 * on iOS Safari (and on many Android browsers), so a sheet sized with
 * `flex: 1` / `'100%'` keeps the height it had before the keyboard appeared —
 * its footer (the Save button) ends up rendered below the visible area,
 * hidden behind the keyboard, exactly as reported. `window.visualViewport`
 * is the standards-track API for the actually-visible area and *does*
 * shrink when the keyboard opens, on both iOS Safari and Chrome/Android.
 */
export function useVisualViewportHeight(): number | null {
  // Start identically during static rendering and browser hydration. Reading
  // `window` here would make the first client render disagree with the HTML
  // generated by Expo Router; the effect updates the value immediately after
  // mount instead.
  const [height, setHeight] = useState<number | null>(null);

  useEffect(() => {
    if (Platform.OS !== 'web' || typeof window === 'undefined' || !window.visualViewport) return undefined;

    const viewport = window.visualViewport;
    const update = () => setHeight(viewport.height);

    update();
    viewport.addEventListener('resize', update);
    viewport.addEventListener('scroll', update);

    return () => {
      viewport.removeEventListener('resize', update);
      viewport.removeEventListener('scroll', update);
    };
  }, []);

  return height;
}
